[project]
name = 'Health-contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.access_log]
path = 'contracts/access_log.clar'
clarity_version = 2
epoch = 2.5

[contracts.store_form_data]
path = 'contracts/store_form_data.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
